#include <stdio.h>

#define INITIAL_ADDRESS    0x0000
#define INITIAL_BLOCK_SIZE 2

#define CAM_ADDRESS    INITIAL_ADDRESS + INITIAL_BLOCK_SIZE
#define CAM_BLOCK_SIZE 5

#define INIT_OBJS_ADDRESS CAM_ADDRESS + CAM_BLOCK_SIZE

#define OBJ_SET_BLOCK_SIZE        2
#define TMATRIX_BLOCK_SIZE        12
#define TO_INIT_VERTEX_BLOCK_SIZE OBJ_SET_BLOCK_SIZE + TMATRIX_BLOCK_SIZE

#define REQUEST_VALID_TAG  0xAAAA
#define APPROVAL_VALID_TAG 0x5555

#define GPU_VALID_TAG   0xCCCC
#define CAM_VALID_TAG   0x3333

#define OBJ_VALID_TAG   0xEEEE
#define OBJ_DISABLE_TAG ~(OBJ_VALID_TAG) // 0x1111

#define VRTX_VALID_TAG 0x9999
